catalog_name: dsa_sandbox
schema_name: mlops_training
model_name: zone_1_power_estimator
model_artifact_name: randomforest-pipeline-model
experiment_name: /Users/xander.schevenhoven@jumbo.com/mlops_training/week2-notebook2

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test:
  learning_rate_a: 0.02
  learning_rate_b: 0.02
  n_estimators: 1000
  max_depth_a: 6
  max_depth_b: 10

numeric_features:
  - Temperature
  - Humidity
  - Wind Speed
  - general diffuse flows
  - diffuse flows

target: Zone 1 Power Consumption
