name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -e .[dev]

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
